name: publish

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"

jobs:
  release:
    if: ${{ contains(github.event.head_commit.message, 'release:') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install and build
        run: |
          node -e "console.log(process.arch)"  
          npm install -g pnpm@7.25.0
          pnpm -v
          pnpm install
          pnpm build
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
